'use client';
import { ChangeEvent, FormEvent, useEffect, useMemo, useState } from 'react';

type Tool='link'|'password'|'image';
type LinkMap=Record<string,{url:string;created:number}>;
const alphabet='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789';
const sets={upper:'ABCDEFGHJKLMNPQRSTUVWXYZ',lower:'abcdefghijkmnopqrstuvwxyz',digits:'23456789',symbols:'!@#$%&*+-_?'};
function securePick(chars:string){const a=new Uint32Array(1);crypto.getRandomValues(a);return chars[a[0]%chars.length]}
function randomCode(n=6){return Array.from({length:n},()=>securePick(alphabet)).join('')}
function bytes(n:number){if(n<1024)return `${n} B`;if(n<1048576)return `${(n/1024).toFixed(1)} KB`;return `${(n/1048576).toFixed(1)} MB`}

export default function Home(){
 const[tool,setTool]=useState<Tool>('link'),[toast,setToast]=useState('');
 const[url,setUrl]=useState(''),[alias,setAlias]=useState(''),[short,setShort]=useState(''),[linkError,setLinkError]=useState('');
 const[length,setLength]=useState(18),[opts,setOpts]=useState({upper:true,lower:true,digits:true,symbols:true}),[password,setPassword]=useState('');
 const[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState(''),[width,setWidth]=useState(0),[height,setHeight]=useState(0),[ratio,setRatio]=useState(1),[format,setFormat]=useState('webp'),[quality,setQuality]=useState(82),[result,setResult]=useState<{url:string,size:number}|null>(null),[imageError,setImageError]=useState('');
 const notify=(m:string)=>{setToast(m);setTimeout(()=>setToast(''),2200)};
 useEffect(()=>{const code=location.hash.match(/^#\/([\w-]+)$/)?.[1];if(!code)return;try{const map:LinkMap=JSON.parse(localStorage.getItem('alperen_shortlinks')||'{}');if(map[code])location.replace(map[code].url)}catch{}},[]);
 const shorten=(e:FormEvent)=>{e.preventDefault();setLinkError('');try{const parsed=new URL(url);if(!['http:','https:'].includes(parsed.protocol))throw 0;const code=alias.trim()||randomCode();if(!/^[a-zA-Z0-9_-]{3,30}$/.test(code)){setLinkError('Kısa ad 3–30 karakter olmalı; yalnızca harf, rakam, - ve _ kullanılabilir.');return}const map:LinkMap=JSON.parse(localStorage.getItem('alperen_shortlinks')||'{}');if(map[code]&&map[code].url!==url){setLinkError('Bu kısa ad daha önce kullanılmış.');return}map[code]={url:parsed.href,created:Date.now()};localStorage.setItem('alperen_shortlinks',JSON.stringify(map));setShort(`${location.origin}/#/${code}`)}catch{setLinkError('Geçerli bir http:// veya https:// bağlantısı gir.') }};
 const generate=()=>{const enabled=Object.entries(opts).filter(([,v])=>v).map(([k])=>sets[k as keyof typeof sets]);if(!enabled.length)return;const chars=enabled.join('');const out=[...enabled.map(s=>securePick(s))];while(out.length<length)out.push(securePick(chars));for(let i=out.length-1;i>0;i--){const j=crypto.getRandomValues(new Uint32Array(1))[0]%(i+1);[out[i],out[j]]=[out[j],out[i]]}setPassword(out.join(''))};
 useEffect(()=>{generate()},[length,opts]);
 const strength=useMemo(()=>{let pool=(opts.upper?24:0)+(opts.lower?24:0)+(opts.digits?8:0)+(opts.symbols?11:0);const bits=pool?Math.round(length*Math.log2(pool)):0;return bits>=100?['Çok güçlü',100]:bits>=70?['Güçlü',78]:bits>=45?['Orta',52]:['Zayıf',27]},[length,opts]);
 const chooseFile=(e:ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;if(!f.type.startsWith('image/')){setImageError('Lütfen bir görsel dosyası seç.');return}if(preview)URL.revokeObjectURL(preview);const src=URL.createObjectURL(f);const img=new Image();img.onload=()=>{setFile(f);setPreview(src);setWidth(img.naturalWidth);setHeight(img.naturalHeight);setRatio(img.naturalWidth/img.naturalHeight);setResult(null);setImageError('')};img.src=src};
 const resize=(axis:'w'|'h',value:number)=>{if(axis==='w'){setWidth(value);if(ratio)setHeight(Math.max(1,Math.round(value/ratio)))}else{setHeight(value);if(ratio)setWidth(Math.max(1,Math.round(value*ratio)))}};
 const processImage=(e:FormEvent)=>{e.preventDefault();if(!file||!preview)return;setImageError('');if(width<1||height<1||width>8000||height>8000){setImageError('Boyutlar 1 ile 8000 piksel arasında olmalı.');return}const img=new Image();img.onload=()=>{const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const ctx=canvas.getContext('2d')!;if(format==='jpeg'){ctx.fillStyle='#fff';ctx.fillRect(0,0,width,height)}ctx.drawImage(img,0,0,width,height);canvas.toBlob(blob=>{if(!blob){setImageError('Bu tarayıcı seçilen formatı desteklemiyor.');return}if(result)URL.revokeObjectURL(result.url);setResult({url:URL.createObjectURL(blob),size:blob.size})},`image/${format}`,format==='png'?undefined:quality/100)};img.src=preview};
 const download=()=>{if(!result)return;const a=document.createElement('a');a.href=result.url;a.download=`optimize-${Date.now()}.${format==='jpeg'?'jpg':format}`;a.click()};
 const copy=async(text:string)=>{await navigator.clipboard.writeText(text);notify('Panoya kopyalandı')};
 return <main><header className="nav shell"><a className="brand" href="#top"><span className="brand-mark">↗</span><span>KısaLink</span></a><nav>{([['link','Kısa Link'],['password','Parola'],['image','Görsel']] as [Tool,string][]).map(([id,label])=><button className={tool===id?'active':''} onClick={()=>setTool(id)} key={id}>{label}</button>)}</nav></header>
 <section className="hero shell" id="top"><div className="eyebrow"><span/> Ücretsiz, hızlı ve tarayıcıda güvenli</div><h1>Dijital işlerini<br/><em>tek yerde hızlandır.</em></h1><p className="lede">Uzun bağlantıları sadeleştir, güçlü parolalar üret ve görsellerini saniyeler içinde optimize et.</p>
 <div className="workspace">
 {tool==='link'&&<section className="tool"><div className="tool-head"><div><small>01 · BAĞLANTI</small><h2>Linkini kısalt</h2></div><span className="tool-icon">↗</span></div><form onSubmit={shorten}><label>Uzun bağlantı</label><input type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://ornek.com/cok-uzun-bir-baglanti" required/><label>Özel kısa ad <i>opsiyonel</i></label><div className="alias"><span>/</span><input value={alias} onChange={e=>setAlias(e.target.value)} placeholder="kampanyam" maxLength={30}/></div>{linkError&&<p className="error">{linkError}</p>}<button className="primary">Kısa link oluştur <span>→</span></button></form>{short&&<div className="result"><div><small>HAZIR</small><a href={short}>{short}</a></div><button onClick={()=>copy(short)}>Kopyala</button></div>}<p className="privacy">⌁ Kısa bağlantılar bu cihazda saklanır; verilerin sunucuya gönderilmez.</p></section>}
 {tool==='password'&&<section className="tool"><div className="tool-head"><div><small>02 · GÜVENLİK</small><h2>Güçlü parola üret</h2></div><span className="tool-icon">⌘</span></div><div className="password-box"><code>{password||'En az bir karakter grubu seç'}</code><button onClick={generate} aria-label="Yenile">↻</button><button onClick={()=>copy(password)}>Kopyala</button></div><label>Parola uzunluğu <b>{length}</b></label><input type="range" min="4" max="64" value={length} onChange={e=>setLength(+e.target.value)}/><div className="checks">{([['upper','Büyük harf','A–Z'],['lower','Küçük harf','a–z'],['digits','Rakam','0–9'],['symbols','Sembol','!@#']] as const).map(([id,label,meta])=><label key={id}><input type="checkbox" checked={opts[id]} onChange={e=>setOpts({...opts,[id]:e.target.checked})}/><span><strong>{label}</strong><small>{meta}</small></span></label>)}</div><div className="strength"><span style={{width:`${strength[1]}%`}}/><b>{strength[0]}</b></div><p className="privacy">✓ Parola Web Crypto API ile tamamen cihazında oluşturulur.</p></section>}
 {tool==='image'&&<section className="tool image-tool"><div className="tool-head"><div><small>03 · GÖRSEL</small><h2>Görseli optimize et</h2></div><span className="tool-icon">◫</span></div>{!file?<label className="drop"><input type="file" accept="image/*" onChange={chooseFile}/><b>Görsel seç veya buraya bırak</b><span>PNG, JPEG, WebP ve tarayıcının desteklediği formatlar</span></label>:<form onSubmit={processImage}><div className="file-card"><img src={preview} alt="Seçilen görsel"/><div><strong>{file.name}</strong><small>{width} × {height}px · {bytes(file.size)}</small></div><label>Değiştir<input type="file" accept="image/*" onChange={chooseFile}/></label></div><div className="size-grid"><label>Genişlik<input type="number" min="1" max="8000" value={width} onChange={e=>resize('w',+e.target.value)}/></label><label>Yükseklik<input type="number" min="1" max="8000" value={height} onChange={e=>resize('h',+e.target.value)}/></label></div><div className="formats">{['webp','jpeg','png'].map(f=><button type="button" className={format===f?'active':''} onClick={()=>setFormat(f)} key={f}>{f.toUpperCase()}</button>)}</div>{format!=='png'&&<label>Kalite <b>%{quality}</b><input type="range" min="10" max="100" value={quality} onChange={e=>setQuality(+e.target.value)}/></label>}{imageError&&<p className="error">{imageError}</p>}<button className="primary">Görseli işle <span>→</span></button>{result&&<div className="image-result"><img src={result.url} alt="İşlenmiş görsel"/><div><strong>{width} × {height}px · {bytes(result.size)}</strong><small>{file.size>result.size?`%${Math.round((1-result.size/file.size)*100)} daha küçük`:'Yeni görsel hazır'}</small></div><button type="button" onClick={download}>İndir</button></div>}</form>}<p className="privacy">✓ Görsel cihazından dışarı çıkmaz; işlem tarayıcıda yapılır.</p></section>}
 </div><div className="mini-grid"><article onClick={()=>setTool('link')}><b>↗</b><span><strong>Kısa bağlantı</strong>Özel kısa ad ve hızlı kopyalama</span></article><article onClick={()=>setTool('password')}><b>⌁</b><span><strong>Parola üretici</strong>Kriptografik ve özelleştirilebilir</span></article><article onClick={()=>setTool('image')}><b>◫</b><span><strong>Görsel dönüştürücü</strong>WebP, JPEG ve PNG desteği</span></article></div></section><footer>© 2026 Alperen Şenel · Ücretsiz dijital araçlar</footer>{toast&&<div className="toast">✓ {toast}</div>}</main>}
